spring:
  application:
    name: catering-backend
  security:
    jwt:
      secret-key: ${JWT_TOKEN:79da7f18-2a0b-45d3-9cd1-ae10a47694aa}
    user:
      name: ${SECURITY_USERNAME:admin}
      password: ${SECURITY_USERNAME:password}
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /docs
    csrf:
      enabled: true