ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/user"
  user: postgres
  password: password