ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  security:
    jwt:
      secret-key: ${JWT_SECRET:79da7f18-2a0b-45d3-9cd1-ae10a47694aa}
    local:
      secret-key: ${LOCAL_SECRET:487c0c9f-082c-4236-a522-d1d47b64c6c5}
  deployment:
    port: 8081
postgres:
  url: "jdbc:postgresql://localhost:5433/user"
  user: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:password}